vim_plugin_task "zencoding", "git://github.com/mattn/zencoding-vim.git"
# vim_plugin_task "minibufexpl", "git://github.com/fholgado/minibufexpl.vim.git"
vim_plugin_task "vim-pony", "git://github.com/rainerborene/vim-pony.git"
vim_plugin_task "surround", "git://github.com/tpope/vim-surround.git"
vim_plugin_task "autoclose", "git://github.com/vim-scripts/AutoClose.git"
